apiVersion: v1
kind: Service
metadata:
  name: helios-server
  namespace: igti-pa
  labels:
    app: helios-server
spec:
  selector:
    app: helios-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helios-deployment
  namespace: igti-pa
  labels:
    app: helios-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helios-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: helios-server
    spec:
      containers:
      - name: helios-server
        image: scavassa/helios-server
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: helios-env
        ports:
        - containerPort: 8000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 8000